### ISSUE TITLE
Скриншоты

### ISSUE THREAD

**Issue by gans13** [SpecialForce3331/sldap#3]
Приветствую! Есть ли возможность выложить пару скринов?

**Comment by SpecialForce3331** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/3347245/6415071/39b2ee3a-bebe-11e4-8ab6-76b0cdc36077.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3347245/6415077/4c9728c2-bebe-11e4-8739-da6ca03a579e.png)

**Comment by SpecialForce3331** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/3347245/6415903/d670b16c-bec3-11e4-9d68-1f417f54ba84.png)

**Comment by gans13** [comment]
Спасибо, буду пробовать на днях

**Comment by gans13** [comment]
Будет отрабатывать, если ко всему этому делу прикрутить wccp ?

**Comment by SpecialForce3331** [comment]
Он обрабатывает все что есть в файлике /var/log/squid/access.log

**Comment by SpecialForce3331** [comment]
Если будут вопросы по установке, пиши.
